package Protocol;

public enum PlayerState {
    INIT_STATE,
    WAITING_FOR_GAME_BEGIN,
    PLACING_SHIPS,
    PLACING_CARRIER,
    PLACING_BATTLESHIP,
    PLACING_CRUISER,
    PLACING_SUBMARINE,
    PLACING_DESTROYER,
    READY,
    MAKING_MOVE,
    WAITING_FOR_MOVE,
    WAITING_FOR_RESULT,
    WINNER,
    LOSER
}
